default: &default
  username: teejayvanslyke
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: digestif_development

test:
  <<: *default
  database: digestif_test

